apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    field.cattle.io/creatorId: user-tfgpg
  creationTimestamp: 2018-08-21T03:40:23Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-08-23T02:22:43Z
  finalizers:
  - foregroundDeletion
  generation: 14
  labels:
    workload.user.cattle.io/workloadselector: deployment-autoever-bonggi
  name: bonggi
  namespace: autoever
  resourceVersion: "37924251"
  selfLink: /apis/extensions/v1beta1/namespaces/autoever/deployments/bonggi
  uid: efa177c2-a4f3-11e8-b0a2-005056ae4fba
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-autoever-bonggi
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        workload.cattle.io/state: '{"aHBjLWRvY2tlcjAy":"c-sxf4p:m-7d54e6150d60"}'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-autoever-bonggi
    spec:
      affinity: {}
      containers:
      - image: docker.hae-hpc.com/ubuntu/ubuntu:xenial
        imagePullPolicy: Always
        name: bonggi
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      nodeName: hpc-docker02
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2018-08-21T05:49:19Z
    lastUpdateTime: 2018-08-21T05:49:19Z
    message: ReplicaSet "bonggi-75d6f95d" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  - lastTransitionTime: 2018-08-21T07:33:29Z
    lastUpdateTime: 2018-08-21T07:33:29Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 14

