apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "trident-etcd"
spec:
  size: 3
  ##TODO
  #backup:
  #  # short snapshot interval for testing, do not use this in production!
  #  backupIntervalInSecond: 30
  #  maxBackups: 5
  #  storageType: "PersistentVolume"
  #  pv:
  #    volumeSizeInMB: 512
  #  autoDelete: true
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls

