kind: ClusterRoleBinding
apiVersion: v1 
metadata:
  name: trident
subjects:
  - kind: ServiceAccount
    name: trident
    namespace: trident
roleRef:
  name: trident
---
kind: ClusterRoleBinding
apiVersion: v1
metadata:
    name: trident-launcher
subjects:
  - kind: ServiceAccount
    name: trident-launcher
    namespace: trident
roleRef:
  name: trident-launcher

