apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trident
  labels:
    app: trident.netapp.io
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trident.netapp.io
    spec:
      serviceAccount: trident
      containers:
      - name: trident-main
        image: netapp/trident:18.07.0
        command:
        - /usr/local/bin/trident_orchestrator
        args:
        - -etcd_v3
        - https://trident-etcd-client:2379
        - -k8s_pod
        #- -k8s_api_server
        #- __KUBERNETES_SERVER__:__KUBERNETES_PORT__
        #- -debug
        volumeMounts:
        - name: client-certs
          mountPath: /root/certs
      volumes:
      - name: client-certs
        secret:
          secretName: etcd-client-tls
